In [1]:
import os
import gc
import warnings

import pandas as pd

import deepmatcher as dm
import torch

In [3]:
os.environ['CUDA_VISIBLE_DEVICES']='1'
print('torch version {}'.format(torch.__version__))
print('CUDA availability {}'.format(torch.cuda.is_available()))
warnings.filterwarnings("ignore", category=DeprecationWarning)

torch version 1.8.1+cu102
CUDA availability True

In [4]:
datadir = '/home/common/aravind/deepmatch_100embedding/data/preprocess_data/2/'

#files = [ 'train_dataset.csv' , 'test_dataset.csv' , 'val_dataset.csv']
files = [ 'train_dataset.csv' , 'val_dataset.csv']


if not os.path.exists(datadir):
    raise Exception(' data dir {} not found'.format(datadir))
else :
    print('datset Found at path : {}'.format(datadir))
    for file in files:
        if os.path.exists(os.path.join(datadir, file)):
            print('File {} Found'.format(file))
        else:
            raise Exception('File {} not Found'.format(file))

datset Found at path : /home/common/aravind/deepmatch_100embedding/data/preprocess_data/2/
File train_dataset.csv Found
File val_dataset.csv Found

In [5]:
train_dataset = pd.read_csv(os.path.join(datadir,files[0]), sep =',', index_col=7)
train_dataset.head()

,left_id,right_id,left_Name,right_Name,left_Brand,right_Brand,label
id,,,,,,,
3809905,staples|23976343,walmart|613604331,"Honey Can Do Bamboo spreader, 7"":box of 48, ba...","Sugarman Candy Clear Plastic Tongs, 6 1/2-Inch...",honey can do,Sugarman Candy,0
6231589,staples|662280,walmart|427704838,"Lysol® All-Purpose Cleaner, Spray, Lemon Breez...",1PCS New Arrival Whiteboard board Eraser Drywi...,Lysol,Cocasasa,0
142858,staples|365378,walmart|37306566,"Brighton Professional 2-Ply Flat Box Tissues, ...","Great Value Flushable Wipes, Fresh Scent, 42 C...",Brighton Professional,Great Value,0
3189751,staples|1101805,walmart|590251474,Tiny Temptations Plastic Tiny Tensils-Asian Ze...,Pacifica Natural Skincare Essential Makeup Rem...,Tiny Temptations,Pacifica,0
3234428,staples|2634892,walmart|36606781,Touch of Color Turquoise Blue Assorted Plastic...,Disney Baby Mickey Mouse Dinnerware Set 5 pc Box,Touch of Color,NaN,0

In [6]:
test_dataset = pd.read_csv(os.path.join(datadir,files[1]), sep =',')
test_dataset.head()

,left_id,right_id,left_Name,right_Name,left_Brand,right_Brand,label,id
0,staples|FALMCSS,walmart|27230383,"Dust-Off® Screen Shammy™ Wipe, Unscented, 12""(...",Puretouch Tush Wipes Flushable - 24 Wipes,Dust-Off,PureTouch,0,6219577
1,staples|111646,walmart|935852407,"Medline Wooden Medical Spoons, 3-5/8"" L, 1000/...","Mainstays Kids Melamine Bowls, 4 Pack, Multipl...",Medline,Mainstays,0,1641434
2,staples|746563,walmart|47703627,"PDI Sani-Hands ALC Hand Wipes, Packets, 100 Count","Grime Boss Unscented Hand Wipes, 24CT",Medical Arts Press,Grime Boss,0,5752893
3,staples|RAC89347CT,walmart|717013182,"Lysol Disinfecting Wipes, Early Morning Breeze...","Wild Republic - Mighty Mini - Hedge Hog 5""",Lysol,NaN,0,5874741
4,staples|2607355,walmart|256232770,"Clorox® Scentiva™ Multi Surface Cleaner Spray,...",4 Piece Ultimate Silicone Basting Brush Set - ...,Clorox,US Kitchen Supply,0,6308344

In [7]:
val_dataset = pd.read_csv(os.path.join(datadir,files[1]), sep =',')
val_dataset.head()

,left_id,right_id,left_Name,right_Name,left_Brand,right_Brand,label,id
0,staples|FALMCSS,walmart|27230383,"Dust-Off® Screen Shammy™ Wipe, Unscented, 12""(...",Puretouch Tush Wipes Flushable - 24 Wipes,Dust-Off,PureTouch,0,6219577
1,staples|111646,walmart|935852407,"Medline Wooden Medical Spoons, 3-5/8"" L, 1000/...","Mainstays Kids Melamine Bowls, 4 Pack, Multipl...",Medline,Mainstays,0,1641434
2,staples|746563,walmart|47703627,"PDI Sani-Hands ALC Hand Wipes, Packets, 100 Count","Grime Boss Unscented Hand Wipes, 24CT",Medical Arts Press,Grime Boss,0,5752893
3,staples|RAC89347CT,walmart|717013182,"Lysol Disinfecting Wipes, Early Morning Breeze...","Wild Republic - Mighty Mini - Hedge Hog 5""",Lysol,NaN,0,5874741
4,staples|2607355,walmart|256232770,"Clorox® Scentiva™ Multi Surface Cleaner Spray,...",4 Piece Ultimate Silicone Basting Brush Set - ...,Clorox,US Kitchen Supply,0,6308344

In [8]:
del val_dataset, train_dataset
gc.collect()

0

In [9]:
dm.data.reset_vector_cache()

In [10]:
train, validation = dm.data.process(path='/home/common/aravind/deepmatch_100embedding/data/preprocess_data/2',
                                          train='train_dataset.csv',
                                          validation='val_dataset.csv',
                                          ignore_columns = ['left_id', 'right_id'],
                                          embeddings ='glove.6B.50d',
                                          embeddings_cache_path ='/mnt/.vector_cache')

In [ ]:
'''train, validation, test = dm.data.process(path='/mnt/deepmatcher/data', \
                                          train='train_dataset.csv',\
                                          validation='val_dataset.csv',\
                                          test='test_dataset.csv',\
                                          ignore_columns = ['amazon_key', 'opd_key'],
                                          embeddings ='glove.6B.50d')'''

In [11]:
model = dm.MatchingModel(attr_summarizer='hybrid')

In [12]:
model.run_train(
    train,
    validation,
    epochs=10,
    batch_size=16,
    best_save_path='/home/common/aravind/deepmatch_100embedding/data/model/paper_product_staples_walmart_e10_9960_50d.pth')

/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py:770: UserWarning: Using non-full backward hooks on a Module that does not take as input a single Tensor or a tuple of Tensors is deprecated and will be removed in future versions. This hook will be missing some of the grad_input. Please use register_full_backward_hook to get the documented behavior.
  warnings.warn("Using non-full backward hooks on a Module that does not take as input a "
/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py:795: UserWarning: Using a non-full backward hook when the forward contains multiple autograd Nodes is deprecated and will be removed in future versions. This hook will be missing some grad_input. Please use register_full_backward_hook to get the documented behavior.
  warnings.warn("Using a non-full backward hook when the forward contains multiple autograd Nodes "

* Number of trainable parameters: 4096204
===>  TRAIN Epoch 1

/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py:760: UserWarning: Using non-full backward hooks on a Module that does not return a single Tensor or a tuple of Tensors is deprecated and will be removed in future versions. This hook will be missing some of the grad_output. Please use register_full_backward_hook to get the documented behavior.
  warnings.warn("Using non-full backward hooks on a Module that does not return a "
/usr/local/lib/python3.6/dist-packages/torch/nn/functional.py:2611: UserWarning: reduction: 'mean' divides the total loss by both the batch size and the support size.'batchmean' divides only by the batch size, and aligns with the KL div math definition.'mean' will be changed to behave the same as 'batchmean' in the next major release.
  "reduction: 'mean' divides the total loss by both the batch size and the support size."
0% [██████████████████████████████] 100% | ETA: 00:00:00
Total time elapsed: 00:00:48

Finished Epoch 1 || Run Time:   40.8 | Load Time:    7.5 || F1:   8.40 | Prec:  27.78 | Rec:   4.95 || Ex/s: 165.81

===>  EVAL Epoch 1

0% [███████████████████████] 100% | ETA: 00:00:00
Total time elapsed: 00:00:06

Finished Epoch 1 || Run Time:    4.7 | Load Time:    1.8 || F1:  28.57 | Prec:  50.00 | Rec:  20.00 || Ex/s: 294.11

* Best F1: tensor(28.5714, device='cuda:0')
Saving best model...
Done.
---------------------

===>  TRAIN Epoch 2

0% [██████████████████████████████] 100% | ETA: 00:00:00
Total time elapsed: 00:00:48

Finished Epoch 2 || Run Time:   40.7 | Load Time:    7.6 || F1:  40.60 | Prec:  84.38 | Rec:  26.73 || Ex/s: 165.87

===>  EVAL Epoch 2

0% [███████████████████████] 100% | ETA: 00:00:00
Total time elapsed: 00:00:06

Finished Epoch 2 || Run Time:    4.8 | Load Time:    1.8 || F1:  61.54 | Prec:  50.00 | Rec:  80.00 || Ex/s: 286.92

* Best F1: tensor(61.5385, device='cuda:0')
Saving best model...
Done.
---------------------

===>  TRAIN Epoch 3

0% [██████████████████████████████] 100% | ETA: 00:00:00
Total time elapsed: 00:00:48

Finished Epoch 3 || Run Time:   41.4 | Load Time:    7.6 || F1:  70.24 | Prec:  88.06 | Rec:  58.42 || Ex/s: 163.30

===>  EVAL Epoch 3

0% [███████████████████████] 100% | ETA: 00:00:00
Total time elapsed: 00:00:06

Finished Epoch 3 || Run Time:    4.8 | Load Time:    1.8 || F1:  80.00 | Prec:  80.00 | Rec:  80.00 || Ex/s: 287.90

* Best F1: tensor(80., device='cuda:0')
Saving best model...
Done.
---------------------

===>  TRAIN Epoch 4

0% [██████████████████████████████] 100% | ETA: 00:00:00
Total time elapsed: 00:00:48

Finished Epoch 4 || Run Time:   41.0 | Load Time:    7.6 || F1:  76.67 | Prec:  87.34 | Rec:  68.32 || Ex/s: 164.68

===>  EVAL Epoch 4

0% [███████████████████████] 100% | ETA: 00:00:00
Total time elapsed: 00:00:06

Finished Epoch 4 || Run Time:    4.7 | Load Time:    1.8 || F1:  66.67 | Prec:  57.14 | Rec:  80.00 || Ex/s: 293.87

---------------------

===>  TRAIN Epoch 5

0% [██████████████████████████████] 100% | ETA: 00:00:00
Total time elapsed: 00:00:48

Finished Epoch 5 || Run Time:   40.9 | Load Time:    7.6 || F1:  87.37 | Prec:  93.26 | Rec:  82.18 || Ex/s: 165.10

===>  EVAL Epoch 5

0% [███████████████████████] 100% | ETA: 00:00:00
Total time elapsed: 00:00:06

Finished Epoch 5 || Run Time:    4.8 | Load Time:    1.8 || F1:  72.73 | Prec:  66.67 | Rec:  80.00 || Ex/s: 286.99

---------------------

===>  TRAIN Epoch 6

0% [██████████████████████████████] 100% | ETA: 00:00:00
Total time elapsed: 00:00:48

Finished Epoch 6 || Run Time:   41.3 | Load Time:    7.6 || F1:  96.48 | Prec:  97.96 | Rec:  95.05 || Ex/s: 163.66

===>  EVAL Epoch 6

0% [███████████████████████] 100% | ETA: 00:00:00
Total time elapsed: 00:00:06

Finished Epoch 6 || Run Time:    4.8 | Load Time:    1.8 || F1:  72.73 | Prec:  66.67 | Rec:  80.00 || Ex/s: 284.25

---------------------

===>  TRAIN Epoch 7

0% [██████████████████████████████] 100% | ETA: 00:00:00
Total time elapsed: 00:00:48

Finished Epoch 7 || Run Time:   41.5 | Load Time:    7.7 || F1:  97.98 | Prec: 100.00 | Rec:  96.04 || Ex/s: 163.04

===>  EVAL Epoch 7

0% [███████████████████████] 100% | ETA: 00:00:00
Total time elapsed: 00:00:06

Finished Epoch 7 || Run Time:    4.8 | Load Time:    1.8 || F1:  80.00 | Prec:  80.00 | Rec:  80.00 || Ex/s: 287.67

---------------------

===>  TRAIN Epoch 8

0% [██████████████████████████████] 100% | ETA: 00:00:00
Total time elapsed: 00:00:48

Finished Epoch 8 || Run Time:   41.1 | Load Time:    7.7 || F1:  98.49 | Prec: 100.00 | Rec:  97.03 || Ex/s: 164.37

===>  EVAL Epoch 8

0% [███████████████████████] 100% | ETA: 00:00:00
Total time elapsed: 00:00:06

Finished Epoch 8 || Run Time:    4.8 | Load Time:    1.8 || F1:  80.00 | Prec:  80.00 | Rec:  80.00 || Ex/s: 286.94

---------------------

===>  TRAIN Epoch 9

0% [██████████████████████████████] 100% | ETA: 00:00:00
Total time elapsed: 00:00:47

Finished Epoch 9 || Run Time:   40.6 | Load Time:    7.5 || F1:  98.49 | Prec: 100.00 | Rec:  97.03 || Ex/s: 166.77

===>  EVAL Epoch 9

0% [███████████████████████] 100% | ETA: 00:00:00
Total time elapsed: 00:00:06

Finished Epoch 9 || Run Time:    4.7 | Load Time:    1.8 || F1:  90.91 | Prec:  83.33 | Rec: 100.00 || Ex/s: 295.09

* Best F1: tensor(90.9091, device='cuda:0')
Saving best model...
Done.
---------------------

===>  TRAIN Epoch 10

0% [██████████████████████████████] 100% | ETA: 00:00:00
Total time elapsed: 00:00:48

Finished Epoch 10 || Run Time:   41.0 | Load Time:    7.6 || F1:  98.49 | Prec: 100.00 | Rec:  97.03 || Ex/s: 164.64

===>  EVAL Epoch 10

0% [███████████████████████] 100% | ETA: 00:00:00
Total time elapsed: 00:00:06

Finished Epoch 10 || Run Time:    4.7 | Load Time:    1.8 || F1:  90.91 | Prec:  83.33 | Rec: 100.00 || Ex/s: 290.49

---------------------

Loading best model...
Training done.

tensor(90.9091, device='cuda:0')

In [13]:
model.save_state('/home/common/aravind/deepmatch_100embedding/data/model/paper_product_staples_walmart_e10_9960_50d_state.pth', include_meta=True)

In [14]:
model.run_eval(validation)

===>  EVAL Epoch 9

0% [████████████] 100% | ETA: 00:00:00
Total time elapsed: 00:00:04

Finished Epoch 9 || Run Time:    3.0 | Load Time:    2.0 || F1:  90.91 | Prec:  83.33 | Rec: 100.00 || Ex/s: 382.21

tensor(90.9091, device='cuda:0')

In [15]:
del model , train, validation
gc.collect()

NameError: name 'test' is not defined